### ISSUE TITLE
Problem by editing config.json

### ISSUE THREAD

**Issue by DarkStar0078** [BastienMaes/homebridge-S7#1]
Hello, 

this is a very nice Project and I want to use it in my home. I have already a S7-1200 as home control but the controlling via
WebUI is very slow. 

Then I found Homebridge and your Project and hopefully I get a perfect Smarthome when this works for me :-).

So, how can I add the S7-PLC to my Homebridge, there is always a failure with the code, what I am doing wrong.
This is my Json.config after adding your code:

`{
    "bridge": {
        "name": "Homebridge xxxx",
        "username": "xxxxx",
        "port": xxxxx,
        "pin": "xxxxxxxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "de",
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxxx",
                "password": "xxxxx",
                "countryCode": "xxxxx",
                "platform": "xxxxxxx"
            },
            "defaults": [
                {
                    "id": "bf1bac37340aff8dd6fw34",
                    "device_type": "light"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
    ]
}

{
    "platforms": [
        {
            "platform": "S7",
            "IP": "192.168.0.25",
            "accessories": [
                {
                    "accessory": "S7_LightDimm",
                    "name": "Palier",
                    "DB": 10,
                    "Byte": 598
                },
                {
                    "accessory": "S7_LightBulb",
                    "name": "Chambre",
                    "DB": 10,
                    "Byte": 280,
                    "WriteBitOn": 3,
                    "WriteBitOff": 2,
                    "ReadBitState": 1
                },
                {
                    "accessory": "S7_Sensor",
                    "name": "Température de la chambre",
                    "DB": 10,
                    "Byte": 888
                }
            ]
        }
    ]
}`

When I press save I get a Syntax failure.

Can you help me?

BR 

Sven :-)

**Comment by DarkStar0078** [comment]
Okay, 

I´ve got it, it was a missing comma, and I changed the code.

Now the Plugins works. How do `speak` with the PLC, i want to switch directly 
outputs, is it possible?

BR

Sven :-)

**Comment by Feilner** [comment]
In theory it is possible to switch outputs directly. But not with the current implementation.
The current implementation requires that the request for on/off is done towards an DB by enabling one bit.
This perfectly fits the "normal" use case where you have implemented remote interface that's used by homebridge.

What you ask for is directly writing to the outputs which means the outputs are more or less not controlled by the PLC program.

I made a pull request allowing single bit writes. 
When using that you can easily modify the code to have what you are asking for.

When you set all bits in the config to the same offset and change inside the code:
```
...
    buf[0] = 1;

    // Write single Bit to DB asynchonousely...
    S7Client.WriteArea(S7Client.S7AreaDB, db, ((dbbyte*8) + dbbit), 1, S7Client.S7WLBit, buf, function(err) {
...
```
to

```
...
    buf[0] = status;

    // Write single Bit to DB asynchonousely...
    S7Client.WriteArea(S7Client.S7AreaPA , db, ((dbbyte*8) + dbbit), 1, S7Client.S7WLBit, buf, function(err) {
...
```
Note the different area and buf[0] content.

**Comment by DarkStar0078** [comment]
Hello Feilner, thank you for your support.

Okay, then I will change my Programm in TIA Portal.

Another Problem ist, where can I add username and password, it is necessary 
because I  can not handle user rights in my PLC.

**Comment by Feilner** [comment]
Hello, 
I do not know if I understand the question correctly.
The S7 communication that is used by the homebridge plugin does not support any user authentication (at least not with the series 300/400 where I'm familiar with). That means everyone a snap7 lib that can connect to your network can control your plc. Therefore It would be good to separate the network between "office" and plc. I have planned for it but I don't think I will ever do it.
The homebridge it self supports user authentication for its gui.
From an iOs device you can only control the light bulbs when you connect to homebridge which is protected by a 8 digit code.
That come configuration you can share with others. But when you do it the have access to any output.

When you have a HomePod or AppleTV 4 or newer or a always on iPad at home you can configure them as "Steuerungszentrale" central center which should allow you beside that you can control devices without being in the same WLAN to define which device can be controlled by which person.

**Comment by DarkStar0078** [comment]
Hi, 

okay, I will try to show you my status quo:
I have a S7 1200, programmed in FUP with running Webserver, for
this Webserver I need authentication.

I have programmed the standard switches with the standard
gates (AND, OR ...) (hope its the meaning in English, German it is Gatter)
My Idea now was to change the Program that every switch
is in a DB, by using FC´s. I tried, but in the DB I can not see
any BIT/ Byte information to 'talk' via Homebridge with the S7.

Here is an image, for better understanding:

![Screenshot 2020-09-23 132740](https://user-images.githubusercontent.com/70255244/94007013-0db8d380-fda1-11ea-8c30-a3979380a327.png)

Would be nice if I could control my S7 via Homebridge, otherwise I have to change all relays to shelly devices.

BR 

Sven

**Comment by Feilner** [comment]
Ok in that case we can also switch to German ;-)

Wenn du eine SPS hast wäre es eine Schande diese durch Shelly Geräte zu ersetzen. Ich habe meine komplette Haussteuerrung in einer S7 300 kompatiblen Steuerung realisiert. Inklusive Syslog, PushNotifications, Abfrage vom Wetterbericht, Sonnenstandsberechnung, Feiertagsberechnung, Rollo, Licht, Steckdosen, Verbrauchsmessung, Erzeugen von Einträgen in Volkszaehler.org usw.

In deiner Bild sehe ich im Moment nur Rollos, diese würde ich auch über den Rollo methoden von Homekit machen. Diese sind aber in diesem plug-in noch nicht implementiert. Ich habe dies aber für mich selber vor.
Icons siehe https://homekitnews.com/2019/06/30/icon-changes-to-homekit-in-ios13/blinds-icon/

Daher erst mal meine Empfehlung für eine ganz einfache remote Steuerung von Lampe/Steckdose:
Ich würde einen Datentyp im Beispiel simpleConsumerRemote_t anlegen und diesen als InOut in den FB (Multiinstanz) reingeben. 
Die Instanzen von dem Datentyp legst du ein einen DB und übergibst sie dem FB Aufruf. Die DB Adressen verwendest du dann für die Homebridge.
Hier ein ganz einfaches Beispiel:

![image](https://user-images.githubusercontent.com/6040107/94069606-2e107e80-fdf1-11ea-92ae-e9ec27c26080.png)

**Comment by DarkStar0078** [comment]
:-D auch nicht schlecht :-).

Also, unser Haus wird auch mit einer SPS S71200 gesteuert. Habe 50 Stromstoßrelais (an der S7) im Einsatz um Lampen und Rollos zu steuern. Ich wollte erst alles über den Webserver steuern, allerdings ist mir das zu langsam. Wird zur Zeit alles über Taster gesteuert.

Dann könnte ich ja meinen FUP beibehalten.

So nen FB erstellen:
![OB_FB](https://user-images.githubusercontent.com/70255244/94112088-398d9500-fe45-11ea-9f72-103615287622.png)

So sieht es im FB aus:

![FB_IN](https://user-images.githubusercontent.com/70255244/94113238-def53880-fe46-11ea-8d69-8fab5bdbd25a.png)

Dann in OB und ich erhalte DB:
![DB](https://user-images.githubusercontent.com/70255244/94112153-54f8a000-fe45-11ea-86ff-d7c9e285c7f3.png)

Die große Frage ist jetzt, woher bekomme ich die Adresse? Wo kann ich die ablesen?

So müsste das dann ja dann in der Konfiguration aussehen:

"accessory": "S7_LightBulb",
"name": "Küche_02",
"DB": 15,
"Byte": ???,
"WriteBitOn":???,
"WriteBitOff": ???,
"ReadBitState": ???

Ich habe bei mir auch nur Taster verbaut, also ein Impuls einschalten
nächster Impuls ausschalten. Das gleiche bei den Rollos.

**Comment by Feilner** [comment]
Das mit dem FUP beibehalten ist so eine Sache.
Die Homebridge setzt das Adressierte Speicheradresse nur auf **true** das anschließende setzen auf **false** muss anders als beim Taster vom Programm übernommen werden.

Aber nehmen wir mal an du hättest den obigen FB
In der Spalte Offset steht die Adresse vor dem Punkt die Byte Adresse. Hinter dem Punkt die Bit Adresse.
In der aktuellen Version im main branch von dem Plugin würde es bei Dir im Moment garnicht gehen. Da nur ein komplettes Byte gelesen oder geschrieben wird.
In meinem PullRequest habe ich das auf einzelne Bits umgestellt. Da hier die Adresse zur snap7 lib als Bit offset angegeben wird Kann man also auch Bits in dannachfolgenden Bytes addressieren.

```
"Byte": 0,             <-- Begin ab offset 0 vom DB
"WriteBitOn":0         <-- Bit offset 0  ab Byte 0. Adressiert also 0.0
"WriteBitOff": 1       <-- Bit offset 1  ab Byte 0  Adressiert also 0.1         
"ReadBitState":16        <-Bit offset 16 ab Byte 0, Adressiert also 2.0
```

PS: Ansonsten Verstehe ich dein Programm nicht Oder ist das Pseudo Code?
Wieso zuerst das oder und dann die Flankenerkennung?
Wenn an den einen Eingang z.B. ein Taster hängen würde könnte es aufgrund des Prellens auch zu mehreren Flanken kommen.
(Sollte aber aufgrund der Eingangsträgheit und der Zykluszeit der SPS keine rolle spielen)

/Oliver

**Comment by DarkStar0078** [comment]
Moin Oliver,

Ich habe alles über normale Taster (meist Rollo Taster (Gira Standart) da es keine reinen Serien Taster von Gira gibt) verdrahtet. Die Schalter musste ich mit positiver Flanke vorweg betreiben, sonst hätte ich Disko in der Bude. Das Oder ist für verschiedene Taster, habe alle Taster separat in die "Schaltzentrale" :-D gezogen.

So ein Mist, das wird mit meiner S7 nicht klappen, ich eine 6ES7 214-1AE30-0XB0 v2.2 und kann ich nicht die PUT/GET Funktion aktivieren, also klappt auch Snap7 nicht :-(.

**Comment by DarkStar0078** [comment]
Hallo nochmal,

ich habe mich jetzt dazu entschieden meine S7 upzugraden, habe grad eine neue SPS bestellt. Ich werde berichten :-).

**Comment by Feilner** [comment]
Für welche hast du dich denn entschieden?
Ich habe inzwischen ein eigenes Modul geschrieben das mehr Accessoires unterstützt (Lampe, Thermostat, Rollo, Thermometer, Hygrometer, Steckdose, Präsenzmelder)  sobald ich dazu komme noch die Doku zu machen poste ich den Link.

**Comment by DarkStar0078** [comment]
Moin, ich habe mir die gleiche nochmal geholt, nur halt aktueller, also 214-1AG40 v4.0, das ist am einfachsten. Programm habe ich schon umgebaut und steht bereit zum Upload. Heute soll die neue PLC ankommen, dann wird umgebaut. 

Das hört sich sehr gut an THUMBsUP.

Wenn das alles so klappt kann man hier von einem "kostengünstigen" cloud freien Smart Home sprechen, genial.

**Comment by DarkStar0078** [comment]
Moin Oliver, 
Gestern kam die neue SPS, direkt eingebaut und bespielt, läuft, yes. Allerdings klappen meine Schalter nicht wie gewünscht. Kann ich bei deinem programmierten Schalter noch nen "harten" Schalter hinzufügen? Mit SCL müsste ich mich jetzt erstmal auseinander setzen.

**Comment by Feilner** [comment]
Hallo, 

Inzwischen habe ich mein aufgebohrtes PlugIn hochgeladen: Es ist als plugin unter den Namen "homebridge-plc" zu finden.
Die Anleitung findest du unter https://github.com/Feilner/homebridge-plc#readme

Was du unter einem "harten" Schalter meinst kann ich nur erahnen. Ich denke mal du meinst dass HomeKit ein ganz bestimmtes Bit je nach Schaltzustand hart 0 oder 1. Das würde dann mit folgender config gehen:
            {
                "accessory": "S7_LightBulb",
                "name": "someOther",
                "manufacturer": "single bit for on/off",
                "db": 6094,
                "get_On": 1.1,
                "set_On": 1.1
            },

**Comment by DarkStar0078** [comment]
Hallo Oliver,

neues Plugin installiert. Klappt aber nicht. Ich habe einen Single bit Schalter und einen On Off Bit Schalter probiert, kommt nix bei der SPS an. Wenn ich über Homebridge die Geräte schalte erscheint auch keine Zeile im Protokoll, sowie es beim alten Plugin war. Der Zugriff auf die SPS klappte ja mit dem alten Plugin, also an der SPS sollte es jetzt nicht liegen.

**Comment by Feilner** [comment]
Schalte mal den debug mode von Homebridge ein müsse über -D auf der Komandozeile gehen oder über die gui wenn du Docker benutzt.

**Comment by Feilner** [comment]
Hast du das alte Plugin auch deinstalliert?

**Comment by DarkStar0078** [comment]
Hier das Ergebnis mit Debug ON:
[10/5/2020, 10:44:33] [S7] [myRoom] get On: false (getBit DB15DBX2.0)
[10/5/2020, 10:44:34] [S7] [someOther] set On: true (setBit DB15DBX0.0)
[10/5/2020, 10:44:34] [S7] [someOther] get On: false (getBit DB15DBX2.0)
[10/5/2020, 10:44:36] [S7] [someOther] get On: false (getBit DB15DBX2.0)
[10/5/2020, 10:44:36] [S7] [myRoom] get On: false (getBit DB15DBX2.0)
[10/5/2020, 10:45:47] [S7] [someOther] get On: false (getBit DB15DBX2.0)
[10/5/2020, 10:45:47] [S7] [myRoom] get On: false (getBit DB15DBX2.0)
[10/5/2020, 10:45:48] [S7] [someOther] set On: true (setBit DB15DBX0.0)
[10/5/2020, 10:45:48] [S7] [someOther] get On: false (getBit DB15DBX2.0)
[10/5/2020, 10:45:50] [S7] [someOther] get On: false (getBit DB15DBX2.0)
[10/5/2020, 10:45:50] [S7] [myRoom] get On: false (getBit DB15DBX2.0)
[10/5/2020, 10:45:50] [S7] [someOther] get On: false (getBit DB15DBX2.0)
[10/5/2020, 10:45:50] [S7] [myRoom] get On: false (getBit DB15DBX2.0)

Das alte Plugin habe ich vorher deinstalliert.

**Comment by Feilner** [comment]
Das schaut doch eigentlich gut aus -> Es funktioniert eigentlich.
Was mich etwas stutzig macht ist dass `someOther `und `myRoom `die gleiche Konfiguration haben also:
Lesen ob Ausgang geschaltet ist an `DB 15  DBX 2.0`
Ausgang schreiben an `DB 15 DBX 0.0`

Im moment würde ich sagen es liegt am SPS Programm. Um das auszuschließen Leg doch mach beides aufeinander also get_On und set_On also z.B. auf 0.0
Dann müsste es von der Anzeige vom Homekit auf jeden fall funktionieren und du kannst dann auch mal den DB beobachten.

**Comment by DarkStar0078** [comment]
Die gleiche Konfiguration war nur Testweise. Beim DB beobachten ist keine Zustandsveränderung zu sehen und da sollte man ja wenigstens das setzen auf 1 sehen. Komisch. Muss denn mehr freigegeben werden als bei dem alten Plugin? Mit dem alten konnte ich ja problemlos schalten.

**Comment by DarkStar0078** [comment]
Okay, habe eine Test DB erstellt, klappt, liegt an meinem Programm.

**Comment by DarkStar0078** [comment]
:-), läuft wunderbar 👍.

Was hast du denn für nen Rolladen Baustein im Tia Portal genommen?

**Comment by Feilner** [comment]
Schreib mir mal eine eMail meine eMail ist mein vorname @ username in Deutschland.
